name: Pollen.jl build - PR preview

on:
  - pull_request

jobs:
  pollen:
    name: "Pollen - Build documentation on push to main"
    uses: "./.github/workflows/pollen.build.yml"
    with:
      tag: pr-${{ github.event.number }}
    secrets: inherit