name: Pollen.jl build - dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pollen:
    name: "Pollen - Build documentation on push to main"
    uses: "lorenzoh/Pollen.jl/.github/workflows/pollen.yml@lo/develop"
    with:
      tag: dev
    secrets:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
